language: python
python:
  - "2.7"
sudo: required
virtualenv:
  system_site_packages: True
 install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coveralls
  - pip install coverage
script:
  - py.test --cov-report term --cov=. tests/test_mydiary.py
after_success:
  - coveralls
