language: python
python:
  - "2.7"
sudo: required
system_site_packages: true
 install:
  - pip install -r requirements.txt
  - pip install pytest
script:
  - py.test --cov-report term --cov=. tests/test_mydiary.py
after_success:
  - coveralls
