language: python
python:
  - "3.4"
cache: pip
before_install:
  - pip install -U pip
  - python setup.py install
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose
script:
  - nosetests --with-coverage --cover-package=mydiaryapp
after_success:
  - coveralls
