language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: True
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coveralls
  - pip install coverage
script:
  - pytest
after_success:
  - coveralls
