language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install pytest pytest-cov
script:
  - pytest --cov=app/
after_success:
  - coveralls
