language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: True
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose
script:
  - nosetests --with-coverage --cover-tests --cover-package=tests
after_success:
  - coveralls
