language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: True
install:
  - pip install -r requirements.txt
  - pip install nose
script:
  - nosetests —with coverage —cover-test —cover-package=(test folder)
after_success:
  - coveralls
