language: python
python:
  - "2.7"
sudo: required
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
  - pip install pytest
script:
  - pytest
after_success:
  - coveralls
