language: python
python:
  - "3.4"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose
script:
  - nosetests --with-coverage --cover-package=app
after_success:
  - coveralls
