language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose
script:
  - nosetests --with-coverage
after_success:
  - coveralls
